<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Teacher List - SNHS Library</title>

<style>

*{
margin:0;
padding:0;
box-sizing:border-box;
}

body{
font-family: Arial, sans-serif;
color:#333;
background:#fff;
}

.header{
text-align:center;
border-bottom:3px solid #1e3a8a;
padding-bottom:15px;
margin-bottom:15px;
}

.school-logo{
width:70px;
height:70px;
object-fit:contain;
}

.school-name{
font-size:22px;
font-weight:bold;
color:#1e3a8a;
margin-top:5px;
}

.school-address{
font-size:12px;
color:#555;
}

.report-title{
font-size:18px;
font-weight:bold;
margin-top:10px;
color:#1e3a8a;
}

.report-meta{
display:flex;
justify-content:space-between;
font-size:12px;
margin-bottom:10px;
color:#666;
}

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
}

thead{
background:#1e3a8a;
color:white;
}

th{
padding:10px;
font-size:12px;
border:1px solid #ddd;
text-align:left;
}

td{
padding:8px;
font-size:11px;
border:1px solid #ddd;
}

tbody tr:nth-child(even){
background:#f9f9f9;
}

.text-center{
text-align:center;
}

.no-print{
margin-bottom:15px;
}

.btn{
padding:6px 12px;
border:none;
cursor:pointer;
font-size:12px;
}

.btn-primary{
background:#1e3a8a;
color:white;
}

.btn-secondary{
background:#6c757d;
color:white;
}

.summary-footer{
margin-top:15px;
font-size:11px;
text-align:right;
color:#555;
}

@page{
size:A4;
margin:15mm;
}

@media print{

.no-print{
display:none;
}

body{
margin:0;
}

thead{
display:table-header-group;
}

tr{
page-break-inside:avoid;
}

}

</style>
</head>

<body>

{{-- Print Controls --}}
<div class="no-print">

<a href="{{ route('teachers.index') }}" class="btn btn-secondary">
← Back
</a>

<button onclick="window.print()" class="btn btn-primary">
Print
</button>

</div>


{{-- School Header --}}
<div class="header">

<img src="{{ asset('images/snhs-logo.png') }}" class="school-logo">

<div class="school-name">
Subic National High School
</div>

<div class="school-address">
Mangan-vaca, Subic, Zambales
</div>

<div class="report-title">
List of Teachers Report
</div>

</div>


{{-- Report Meta --}}
<div class="report-meta">

<div>
<strong>Total Teachers:</strong>
{{ count($teachers) }}
</div>

<div>
<strong>Date:</strong>
{{ now()->format('M d, Y') }}
</div>

<div>
<strong>Time:</strong>
<span id="current-time"></span>
</div>

</div>


{{-- Teachers Table --}}
<table>

<thead>

<tr>

<th style="width:40px;">#</th>
<th style="width:180px;">Name</th>
<th style="width:180px;">Email</th>
<th style="width:80px;">Gender</th>
<th style="width:120px;">Phone</th>
<th style="width:200px;">Address</th>


</tr>

</thead>

<tbody>

@forelse($teachers as $i => $teacher)
<tr>
	<td class="text-center">{{ $i+1 }}</td>
	<td><strong>
		@if(!empty($teacher->last_name) || !empty($teacher->first_name))
			{{ $teacher->last_name }}, {{ $teacher->first_name }}
		@elseif(!empty($teacher->name))
			{{ $teacher->name }}
		@else
			-
		@endif
	</strong></td>
	<td>{{ $teacher->email ?? '-' }}</td>
	<td>{{ ucfirst($teacher->gender) ?? '-' }}</td>
	<td>{{ $teacher->phone_number ?? '-' }}</td>
	<td>{{ \Illuminate\Support\Str::limit($teacher->address,40) ?? '-' }}</td>
</tr>

@empty

<tr>

<td colspan="7" class="text-center" style="padding:20px;">
No teachers found in the system
</td>

</tr>

@endforelse

</tbody>

</table>


<div class="summary-footer">
Generated by SNHS Library System
</div>


<script>

function updateTime(){

const now = new Date()

let h = now.getHours()
let m = now.getMinutes()

let ampm = h >= 12 ? "PM" : "AM"

h = h % 12
h = h ? h : 12

m = m < 10 ? "0"+m : m

document.getElementById("current-time").innerText = h+":"+m+" "+ampm

}

updateTime()
setInterval(updateTime,1000)

window.addEventListener("load",function(){

setTimeout(function(){

window.print()

},300)

})

</script>

</body>
</html>